# Data Pre-Processing with Pandas

In this section, our core focus will be using a dataset developed by Microsoft for training purposes in SQL server, known the Adventureworks Cycles 2014OLTP Database.

* It is based on a fictitious company called Adventure Works Cycles (AWC), a multinational manufacturer and seller of bicycles and accessories.
* The company is based in Bothell, Washington, USA and has regional sales offices in several countries.
* We will be looking at a single table from this database, the Production.Product table, which outlines some of the products this company sells.


We will examine this table to earn how to wrangle and clean Pandas data structures. At a high-level, this lesson will cover:

<!--
* **[Adventure Works Cycles Data Dictionary](preprocessing.md#wine-review-data-dictionary)**
* **[Wrangling Data](preprocessing.md#wrangling-data)**
* **[Selecting Data](preprocessing.md#selecting-data)**
	* **[Single Values](preprocessing.md#single-values)**
	* **[Subsetting & Slicing](preprocessing.md#subsetting--slicing)**
* **[Cleaning & Organizing Data](preprocessing.md#cleaning--organizing-data)**
	* **[Editing](preprocessing.md#editing)**
	* **[Null Values](preprocessing.md#null-values)**
	* **[Duplicates](preprocessing.md#duplicates)**
	* **[Sorting](preprocessing.md#sorting)**
-->

## Data Dictionary

In [50]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
ad_cycle = pd.read_csv('/content/gdrive/My Drive/PyDev/raw_data/production.product.tsv', sep='\t')


Every good dataset has a **data dictionary**. Essentially, it lists each field in the data and provides a contextual description. It serves as a good frame of reference for anyone not diving directly into the data.

In [14]:
cols = ad_cycle.columns
for idx, col in enumerate(cols):
  print(idx+1, col)

1 ProductID
2 Name
3 ProductNumber
4 MakeFlag
5 FinishedGoodsFlag
6 Color
7 SafetyStockLevel
8 ReorderPoint
9 StandardCost
10 ListPrice
11 Size
12 SizeUnitMeasureCode
13 WeightUnitMeasureCode
14 Weight
15 DaysToManufacture
16 ProductLine
17 Class
18 Style
19 ProductSubcategoryID
20 ProductModelID
21 SellStartDate
22 SellEndDate
23 DiscontinuedDate
24 rowguid
25 ModifiedDate

## Wrangling Data

After your initial import of some dataset, you'll want to do a gut check to make sure everything is in place. Here are the kind of very basic properties you might want to check:

### `df.info()` -- returns index, datatype and memory information

In [21]:
ad_cycle.info() # this will simply output whatever is returned by calling the `info` method on ad_cycle

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 25 columns):
ProductID                504 non-null int64
Name                     504 non-null object
ProductNumber            504 non-null object
MakeFlag                 504 non-null int64
FinishedGoodsFlag        504 non-null int64
Color                    256 non-null object
SafetyStockLevel         504 non-null int64
ReorderPoint             504 non-null int64
StandardCost             504 non-null float64
ListPrice                504 non-null float64
Size                     211 non-null object
SizeUnitMeasureCode      176 non-null object
WeightUnitMeasureCode    205 non-null object
Weight                   205 non-null float64
DaysToManufacture        504 non-null int64
ProductLine              278 non-null object
Class                    247 non-null object
Style                    211 non-null object
ProductSubcategoryID     295 non-null float64
ProductModelID           295 non-null float64
SellStartDate            504 non-null object
SellEndDate              98 non-null object
DiscontinuedDate         0 non-null float64
rowguid                  504 non-null object
ModifiedDate             504 non-null object
dtypes: float64(6), int64(6), object(13)
memory usage: 98.5+ KB

### `df.shape` -- returns the number of rows and columns in a data frame

In [19]:
ad_cycle.shape

(504, 25)

### `len(obj)` -- returns # of rows in the object data (*S & df)

In [20]:
len(ad_cycle)

504

### `obj.size` -- returns # of elements in the object (*S & df)

In [22]:
ad_cycle.size

12600

### `df.index` -- returns index of the rows specifically (*S & df)

In [23]:
ad_cycle.index

RangeIndex(start=0, stop=504, step=1)

### `df.columns` -- returns the column labels of the DataFrame.

In [24]:
ad_cycle.columns

Index(['ProductID', 'Name', 'ProductNumber', 'MakeFlag', 'FinishedGoodsFlag',
       'Color', 'SafetyStockLevel', 'ReorderPoint', 'StandardCost',
       'ListPrice', 'Size', 'SizeUnitMeasureCode', 'WeightUnitMeasureCode',
       'Weight', 'DaysToManufacture', 'ProductLine', 'Class', 'Style',
       'ProductSubcategoryID', 'ProductModelID', 'SellStartDate',
       'SellEndDate', 'DiscontinuedDate', 'rowguid', 'ModifiedDate'],
      dtype='object')

### `df.head(n)` -- returns last n rows of a data frame

In [25]:
ad_cycle.head() # n is 5 by default

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
0,1,Adjustable Race,AR-5381,0,0,NaN,1000,750,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{694215B7-08F7-4C0D-ACB1-D734BA44C0C8},2014-02-08 10:01:36.827000000
1,2,Bearing Ball,BA-8327,0,0,NaN,1000,750,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{58AE3C20-4F3A-4749-A7D4-D568806CC537},2014-02-08 10:01:36.827000000
2,3,BB Ball Bearing,BE-2349,1,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{9C21AED2-5BFA-4F18-BCB8-F11638DC2E4E},2014-02-08 10:01:36.827000000
3,4,Headset Ball Bearings,BE-2908,0,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{ECFED6CB-51FF-49B5-B06C-7D8AC834DB8B},2014-02-08 10:01:36.827000000
4,316,Blade,BL-2036,1,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{E73E9750-603B-4131-89F5-3DD15ED5FF80},2014-02-08 10:01:36.827000000

### `df.tail(n)` -- returns last n rows of a data frame

In [26]:
ad_cycle.tail()

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
499,995,ML Bottom Bracket,BB-8107,1,1,NaN,500,375,44.9506,101.24,...,NaN,M,NaN,5.0,96.0,2013-05-30 00:00:00,NaN,NaN,{71AB847F-D091-42D6-B735-7B0C2D82FC84},2014-02-08 10:01:36.827000000
500,996,HL Bottom Bracket,BB-9108,1,1,NaN,500,375,53.9416,121.49,...,NaN,H,NaN,5.0,97.0,2013-05-30 00:00:00,NaN,NaN,{230C47C5-08B2-4CE3-B706-69C0BDD62965},2014-02-08 10:01:36.827000000
501,997,"Road-750 Black, 44",BK-R19B-44,1,1,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30 00:00:00,NaN,NaN,{44CE4802-409F-43AB-9B27-CA53421805BE},2014-02-08 10:01:36.827000000
502,998,"Road-750 Black, 48",BK-R19B-48,1,1,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30 00:00:00,NaN,NaN,{3DE9A212-1D49-40B6-B10A-F564D981DBDE},2014-02-08 10:01:36.827000000
503,999,"Road-750 Black, 52",BK-R19B-52,1,1,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30 00:00:00,NaN,NaN,{AE638923-2B67-4679-B90E-ABBAB17DCA31},2014-02-08 10:01:36.827000000

### `df.copy()` -- create a deep copy of the object (*S & df)

In [28]:
ad_cycle.copy()

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
0,1,Adjustable Race,AR-5381,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{694215B7-08F7-4C0D-ACB1-D734BA44C0C8},2014-02-08 10:01:36.827000000
1,2,Bearing Ball,BA-8327,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{58AE3C20-4F3A-4749-A7D4-D568806CC537},2014-02-08 10:01:36.827000000
2,3,BB Ball Bearing,BE-2349,1,0,NaN,800,600,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{9C21AED2-5BFA-4F18-BCB8-F11638DC2E4E},2014-02-08 10:01:36.827000000
3,4,Headset Ball Bearings,BE-2908,0,0,NaN,800,600,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{ECFED6CB-51FF-49B5-B06C-7D8AC834DB8B},2014-02-08 10:01:36.827000000
4,316,Blade,BL-2036,1,0,NaN,800,600,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{E73E9750-603B-4131-89F5-3DD15ED5FF80},2014-02-08 10:01:36.827000000
5,317,LL Crankarm,CA-5965,0,0,Black,500,375,0.0000,0.00,...,NaN,L,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{3C9D10B7-A6B2-4774-9963-C19DCEE72FEA},2014-02-08 10:01:36.827000000
6,318,ML Crankarm,CA-6738,0,0,Black,500,375,0.0000,0.00,...,NaN,M,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{EABB9A92-FA07-4EAB-8955-F0517B4A4CA7},2014-02-08 10:01:36.827000000
7,319,HL Crankarm,CA-7457,0,0,Black,500,375,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{7D3FD384-4F29-484B-86FA-4206E276FE58},2014-02-08 10:01:36.827000000
8,320,Chainring Bolts,CB-2903,0,0,Silver,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{7BE38E48-B7D6-4486-888E-F53C26735101},2014-02-08 10:01:36.827000000
9,321,Chainring Nut,CN-6137,0,0,Silver,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{3314B1D7-EF69-4431-B6DD-DC75268BD5DF},2014-02-08 10:01:36.827000000
10,322,Chainring,CR-7833,0,0,Black,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{F0AC2C4D-1A1F-4E3C-B4D9-68AEA0EC1CE4},2014-02-08 10:01:36.827000000
11,323,Crown Race,CR-9981,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{51A32CA6-65A1-4C31-AF2B-D9E4F5D631D4},2014-02-08 10:01:36.827000000
12,324,Chain Stays,CS-2812,1,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{FE0678ED-AEF2-4C58-A450-8151CC24DDD8},2014-02-08 10:01:36.827000000
13,325,Decal 1,DC-8732,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{05CE123C-A402-478E-AE9B-75D7727AEAAD},2014-02-08 10:01:36.827000000
14,326,Decal 2,DC-9824,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{A56851F9-1CD7-4E2F-8779-2E773E1B5209},2014-02-08 10:01:36.827000000
15,327,Down Tube,DT-2377,1,0,NaN,800,600,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{1DAD47DD-E259-42B8-B8B4-15A0B7D21B2F},2014-02-08 10:01:36.827000000
16,328,Mountain End Caps,EC-M092,1,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{6070B1EA-59B7-4F8B-950F-2BE07D00449D},2014-02-08 10:01:36.827000000
17,329,Road End Caps,EC-R098,1,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{88399D13-719E-4545-81D6-F0650F372FA2},2014-02-08 10:01:36.827000000
18,330,Touring End Caps,EC-T209,1,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{6903CE24-D0CE-4191-9198-4231DE37A929},2014-02-08 10:01:36.827000000
19,331,Fork End,FE-3760,1,0,NaN,800,600,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{C91D602E-DA52-43D2-BD7E-EB110A9392B9},2014-02-08 10:01:36.827000000
20,332,Freewheel,FH-2981,0,0,Silver,500,375,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{D864879A-E8B1-4F7B-BAFA-1F136089C2C8},2014-02-08 10:01:36.827000000
21,341,Flat Washer 1,FW-1000,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{A3F2FA3A-22E1-43D8-A131-A9B89C32D8EA},2014-02-08 10:01:36.827000000
22,342,Flat Washer 6,FW-1200,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{331ADDEC-E9B9-4A7E-9324-42069C2DCDC4},2014-02-08 10:01:36.827000000
23,343,Flat Washer 2,FW-1400,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{84A3473E-AE26-4A21-81B9-60BB418A79B2},2014-02-08 10:01:36.827000000
24,344,Flat Washer 9,FW-3400,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{0AE4CE60-5242-48F5-ADA1-3013FF45F969},2014-02-08 10:01:36.827000000
25,345,Flat Washer 4,FW-3800,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{2C1C58B4-234C-4B3A-8C8E-84524AC05EEA},2014-02-08 10:01:36.827000000
26,346,Flat Washer 3,FW-5160,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{590C2C3F-A8B6-42B5-9412-D655E37F0EAE},2014-02-08 10:01:36.827000000
27,347,Flat Washer 8,FW-5800,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{1B73F5FE-AB85-49FC-99AD-0500CEBDA91D},2014-02-08 10:01:36.827000000
28,348,Flat Washer 5,FW-7160,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{D182CF18-4DDF-429B-A0DF-DE1CFC92622D},2014-02-08 10:01:36.827000000
29,349,Flat Washer 7,FW-9160,0,0,NaN,1000,750,0.0000,0.00,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{7E55F64D-EA3C-45FF-BE72-F7F7B9D61A79},2014-02-08 10:01:36.827000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,970,"Touring-2000 Blue, 46",BK-T44U-46,1,1,Blue,100,75,755.1508,1214.85,...,T,M,U,3.0,35.0,2013-05-30 00:00:00,NaN,NaN,{C0009006-715F-4B76-A05A-1A0D3ADFB49A},2014-02-08 10:01:36.827000000
475,971,"Touring-2000 Blue, 50",BK-T44U-50,1,1,Blue,100,75,755.1508,1214.85,...,T,M,U,3.0,35.0,2013-05-30 00:00:00,NaN,NaN,{84ABDA8F-0007-4BCA-9A61-B2DEA58866C3},2014-02-08 10:01:36.827000000
476,972,"Touring-2000 Blue, 54",BK-T44U-54,1,1,Blue,100,75,755.1508,1214.85,...,T,M,U,3.0,35.0,2013-05-30 00:00:00,NaN,NaN,{6DCFE2A3-3555-44E4-9116-6F6DBE448B8B},2014-02-08 10:01:36.827000000
477,973,"Road-350-W Yellow, 40",BK-R79Y-40,1,1,Yellow,100,75,1082.5100,1700.99,...,R,M,W,2.0,27.0,2013-05-30 00:00:00,NaN,NaN,{237B16D9-53F2-4FD4-BEFE-48209E57AEC3},2014-02-08 10:01:36.827000000
478,974,"Road-350-W Yellow, 42",BK-R79Y-42,1,1,Yellow,100,75,1082.5100,1700.99,...,R,M,W,2.0,27.0,2013-05-30 00:00:00,NaN,NaN,{80BD3F8B-42C7-43D8-91F5-9FB6175287AF},2014-02-08 10:01:36.827000000
479,975,"Road-350-W Yellow, 44",BK-R79Y-44,1,1,Yellow,100,75,1082.5100,1700.99,...,R,M,W,2.0,27.0,2013-05-30 00:00:00,NaN,NaN,{0C61E8AF-003D-4E4B-B5B7-02F01A26BE26},2014-02-08 10:01:36.827000000
480,976,"Road-350-W Yellow, 48",BK-R79Y-48,1,1,Yellow,100,75,1082.5100,1700.99,...,R,M,W,2.0,27.0,2013-05-30 00:00:00,NaN,NaN,{EC4284DC-85FA-44A8-89EC-77FC9B71720A},2014-02-08 10:01:36.827000000
481,977,"Road-750 Black, 58",BK-R19B-58,1,1,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30 00:00:00,NaN,NaN,{87B81A1A-A5B5-43D2-A20D-0230800490B9},2014-02-08 10:01:36.827000000
482,978,"Touring-3000 Blue, 44",BK-T18U-44,1,1,Blue,100,75,461.4448,742.35,...,T,L,U,3.0,36.0,2013-05-30 00:00:00,NaN,NaN,{4F638E15-2ED0-4193-90CE-47DA580E01DD},2014-02-08 10:01:36.827000000
483,979,"Touring-3000 Blue, 50",BK-T18U-50,1,1,Blue,100,75,461.4448,742.35,...,T,L,U,3.0,36.0,2013-05-30 00:00:00,NaN,NaN,{DE305B62-88FC-465B-B23D-D8C0F7E6D361},2014-02-08 10:01:36.827000000
484,980,"Mountain-400-W Silver, 38",BK-M38S-38,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{7A927632-99A4-4F24-ADCE-0062D2D113D9},2014-02-08 10:01:36.827000000
485,981,"Mountain-400-W Silver, 40",BK-M38S-40,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{0A72791C-A984-4733-AE4E-2B4373CFD7CD},2014-02-08 10:01:36.827000000
486,982,"Mountain-400-W Silver, 42",BK-M38S-42,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{4EA4FE06-AAEA-42D4-A9D9-69F6A9A4A042},2014-02-08 10:01:36.827000000
487,983,"Mountain-400-W Silver, 46",BK-M38S-46,1,1,Silver,100,75,419.7784,769.49,...,M,M,W,1.0,22.0,2013-05-30 00:00:00,NaN,NaN,{0B0C8EE4-FF2D-438E-9CAC-464783B86191},2014-02-08 10:01:36.827000000
488,984,"Mountain-500 Silver, 40",BK-M18S-40,1,1,Silver,100,75,308.2179,564.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{B96C057B-6416-4851-8D59-BCB37C8E6E51},2014-02-08 10:01:36.827000000
489,985,"Mountain-500 Silver, 42",BK-M18S-42,1,1,Silver,100,75,308.2179,564.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{B8D1B5D9-8A39-4097-A04A-56E95559B534},2014-02-08 10:01:36.827000000
490,986,"Mountain-500 Silver, 44",BK-M18S-44,1,1,Silver,100,75,308.2179,564.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{E8CEC794-E8E2-4312-96A7-4832E573D3FC},2014-02-08 10:01:36.827000000
491,987,"Mountain-500 Silver, 48",BK-M18S-48,1,1,Silver,100,75,308.2179,564.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{77EF419F-481F-40B9-BDB9-7E6678E550E3},2014-02-08 10:01:36.827000000
492,988,"Mountain-500 Silver, 52",BK-M18S-52,1,1,Silver,100,75,308.2179,564.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{CAD60945-183E-4AB3-A70C-3F5BAC6BF134},2014-02-08 10:01:36.827000000
493,989,"Mountain-500 Black, 40",BK-M18B-40,1,1,Black,100,75,294.5797,539.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{28287157-3F06-487B-8531-BEE8A37329E4},2014-02-08 10:01:36.827000000
494,990,"Mountain-500 Black, 42",BK-M18B-42,1,1,Black,100,75,294.5797,539.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{F5752C9C-56BA-41A7-83FD-139DA28C15FA},2014-02-08 10:01:36.827000000
495,991,"Mountain-500 Black, 44",BK-M18B-44,1,1,Black,100,75,294.5797,539.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{C7852127-2FB8-4959-B5A3-DE5A8D6445E4},2014-02-08 10:01:36.827000000
496,992,"Mountain-500 Black, 48",BK-M18B-48,1,1,Black,100,75,294.5797,539.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{75752E26-A3B6-4264-9B06-F23A4FBDC5A7},2014-02-08 10:01:36.827000000
497,993,"Mountain-500 Black, 52",BK-M18B-52,1,1,Black,100,75,294.5797,539.99,...,M,L,U,1.0,23.0,2013-05-30 00:00:00,NaN,NaN,{69EE3B55-E142-4E4F-AED8-AF02978FBE87},2014-02-08 10:01:36.827000000
498,994,LL Bottom Bracket,BB-7421,1,1,NaN,500,375,23.9716,53.99,...,NaN,L,NaN,5.0,95.0,2013-05-30 00:00:00,NaN,NaN,{FA3C65CD-0A22-47E3-BDF6-53F1DC138C43},2014-02-08 10:01:36.827000000
499,995,ML Bottom Bracket,BB-8107,1,1,NaN,500,375,44.9506,101.24,...,NaN,M,NaN,5.0,96.0,2013-05-30 00:00:00,NaN,NaN,{71AB847F-D091-42D6-B735-7B0C2D82FC84},2014-02-08 10:01:36.827000000
500,996,HL Bottom Bracket,BB-9108,1,1,NaN,500,375,53.9416,121.49,...,NaN,H,NaN,5.0,97.0,2013-05-30 00:00:00,NaN,NaN,{230C47C5-08B2-4CE3-B706-69C0BDD62965},2014-02-08 10:01:36.827000000
501,997,"Road-750 Black, 44",BK-R19B-44,1,1,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30 00:00:00,NaN,NaN,{44CE4802-409F-43AB-9B27-CA53421805BE},2014-02-08 10:01:36.827000000
502,998,"Road-750 Black, 48",BK-R19B-48,1,1,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30 00:00:00,NaN,NaN,{3DE9A212-1D49-40B6-B10A-F564D981DBDE},2014-02-08 10:01:36.827000000
503,999,"Road-750 Black, 52",BK-R19B-52,1,1,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30 00:00:00,NaN,NaN,{AE638923-2B67-4679-B90E-ABBAB17DCA31},2014-02-08 10:01:36.827000000

### `obj.empty` -- returns booleans for whether object is empty or not

In [29]:
ad_cycle.empty

False

## Selecting Data

We can select data as either single values or we can slice the data in subsets.


#### Single Values

### `df.loc[row_label, col_label]` -- select a single item in a DataFrame by its row and column labels

In [36]:
print("ProductID:", ad_cycle.loc[0,'ProductID'])

print("Name", ad_cycle.loc[0,'Name'])

print("ProductNumber", ad_cycle.loc[0,'ProductNumber'])

ProductID: 1
Name Adjustable Race
ProductNumber AR-5381


### `df.loc[start_row_label : end_row_label, start_col_label : end_col_label]` 

-- select a slice of a DataFrame by starting and ending row/column labels

In [37]:
ad_cycle.loc[0:3, "ProductID":"ProductNumber"]

   ProductID                   Name ProductNumber
0          1        Adjustable Race       AR-5381
1          2           Bearing Ball       BA-8327
2          3        BB Ball Bearing       BE-2349
3          4  Headset Ball Bearings       BE-2908


### `df.iloc[row_index,:]` -- select a row in a DataFrame by index position

In [40]:
ad_cycle.iloc[6:8]

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
6,318,ML Crankarm,CA-6738,0,0,Black,500,375,0.0,0.0,...,NaN,M,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{EABB9A92-FA07-4EAB-8955-F0517B4A4CA7},2014-02-08 10:01:36.827000000
7,319,HL Crankarm,CA-7457,0,0,Black,500,375,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00,NaN,NaN,{7D3FD384-4F29-484B-86FA-4206E276FE58},2014-02-08 10:01:36.827000000

### `s.iloc[index]` -- select a single item by its position

In [42]:
ad_cycle.iloc[0]

ProductID                                                     1
Name                                            Adjustable Race
ProductNumber                                           AR-5381
MakeFlag                                                      0
FinishedGoodsFlag                                             0
Color                                                       NaN
SafetyStockLevel                                           1000
ReorderPoint                                                750
StandardCost                                                  0
ListPrice                                                     0
Size                                                        NaN
SizeUnitMeasureCode                                         NaN
WeightUnitMeasureCode                                       NaN
Weight                                                      NaN
DaysToManufacture                                             0
ProductLine                                                 NaN
Class                                                       NaN
Style                                                       NaN
ProductSubcategoryID                                        NaN
ProductModelID                                              NaN
SellStartDate                               2008-04-30 00:00:00
SellEndDate                                                 NaN
DiscontinuedDate                                            NaN
rowguid                  {694215B7-08F7-4C0D-ACB1-D734BA44C0C8}
ModifiedDate                      2014-02-08 10:01:36.827000000
Name: 0, dtype: object

### `s.loc[index]` -- select a slice of items from a Series

In [45]:
ad_cycle.loc[1]

ProductID                                                     2
Name                                               Bearing Ball
ProductNumber                                           BA-8327
MakeFlag                                                      0
FinishedGoodsFlag                                             0
Color                                                       NaN
SafetyStockLevel                                           1000
ReorderPoint                                                750
StandardCost                                                  0
ListPrice                                                     0
Size                                                        NaN
SizeUnitMeasureCode                                         NaN
WeightUnitMeasureCode                                       NaN
Weight                                                      NaN
DaysToManufacture                                             0
ProductLine                                                 NaN
Class                                                       NaN
Style                                                       NaN
ProductSubcategoryID                                        NaN
ProductModelID                                              NaN
SellStartDate                               2008-04-30 00:00:00
SellEndDate                                                 NaN
DiscontinuedDate                                            NaN
rowguid                  {58AE3C20-4F3A-4749-A7D4-D568806CC537}
ModifiedDate                      2014-02-08 10:01:36.827000000
Name: 1, dtype: object

### Difference between loc and iloc

loc gets rows (or columns) with particular labels from the index. iloc gets rows (or columns) at particular positions in the index (so it only takes integers). [SO](https://stackoverflow.com/questions/31593201/how-are-iloc-ix-and-loc-different)

In [60]:
s2 = pd.Series(np.nan, index=[49,48,47,46,45, 1, 2, 3, 4, 5])
print(s2.iloc[:3])
print('---------------')
print(s2.loc[:3])

49   NaN
48   NaN
47   NaN
dtype: float64
---------------
49   NaN
48   NaN
47   NaN
46   NaN
45   NaN
1    NaN
2    NaN
3    NaN
dtype: float64